id: I9999326F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:31:54+00:00'
last_modified: '2022-06-08T10:45:08.770172+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD225
  title: རྗེ་ལམ་རིམ་པ་ངག་དབང་ཕུན་ཚོགས་ཀྱི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '9464':
      image_group_id: I2PD18800
      title: ''
      total_pages: 334
      order: 1
      base_file: 9464.txt
    AD3F:
      image_group_id: I2PD18801
      title: ''
      total_pages: 314
      order: 2
      base_file: AD3F.txt
    E4B3:
      image_group_id: I2PD18802
      title: ''
      total_pages: 364
      order: 3
      base_file: E4B3.txt
    03AB:
      image_group_id: I2PD18803
      title: ''
      total_pages: 370
      order: 4
      base_file: 03AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
